export const mockRunningAuctionResponse = [
    {
        uuid: "ae80b321-7ecb-480b-b6a5-50d36641eaa2",
        state: 2,
        endingTime: "2021-09-22T11:26:48.069Z",
        remainingTimeInSeconds: 511396,
        remainingTimeForInstantPurchaseInSeconds: null,
        instantPurchasePossibleUntil: null,
        _fk_uuid_highestBiddingBuyerUser: null,
        currentHighestBidValue: 573,
        currentHighestBidValueNet: 573,
        minimumRequiredAsk: 8258,
        minimumRequiredAskNet: 8258,
        numBids: 0,
        amIHighestBidder: false,
        biddingAgentValue: null,
        isMinAskReached: false,
        isCrossBorderNetSale: false,
    },
    {
        uuid: "2c8e1209-9e06-4684-b18f-d0bcf1b7df3e",
        state: 2,
        endingTime: "2021-09-22T11:21:48.069Z",
        remainingTimeInSeconds: 511096,
        remainingTimeForInstantPurchaseInSeconds: null,
        instantPurchasePossibleUntil: null,
        _fk_uuid_highestBiddingBuyerUser: null,
        currentHighestBidValue: 227,
        currentHighestBidValueNet: 227,
        minimumRequiredAsk: 10264,
        minimumRequiredAskNet: 10264,
        numBids: 0,
        amIHighestBidder: false,
        biddingAgentValue: null,
        isMinAskReached: false,
        isCrossBorderNetSale: false,
    },
    {
        uuid: "b7e72fb0-3ecc-450f-b777-b141e2c880bc",
        state: 2,
        endingTime: "2021-09-23T08:00:00.000Z",
        remainingTimeInSeconds: 585388,
        remainingTimeForInstantPurchaseInSeconds: null,
        instantPurchasePossibleUntil: null,
        _fk_uuid_highestBiddingBuyerUser: null,
        currentHighestBidValue: 61,
        currentHighestBidValueNet: 72.59,
        minimumRequiredAsk: 6083,
        minimumRequiredAskNet: 7238.77,
        numBids: 0,
        amIHighestBidder: false,
        biddingAgentValue: null,
        isMinAskReached: false,
        isCrossBorderNetSale: false,
    },
    {
        uuid: "1408c650-6c4d-4a73-8c91-36e0a486e3dd",
        state: 2,
        endingTime: "2021-09-30T17:06:00.000Z",
        remainingTimeInSeconds: 1222948,
        remainingTimeForInstantPurchaseInSeconds: null,
        instantPurchasePossibleUntil: null,
        _fk_uuid_highestBiddingBuyerUser: null,
        currentHighestBidValue: 1440,
        currentHighestBidValueNet: 1713.6,
        minimumRequiredAsk: 22411,
        minimumRequiredAskNet: 26669.09,
        numBids: 0,
        amIHighestBidder: false,
        biddingAgentValue: null,
        isMinAskReached: false,
        isCrossBorderNetSale: false,
    },
];
